using EasyRent.Infrastructure.Abstractions.DocumentStore;

namespace EasyRent.Reservation.Infrastructure.Configurations;

public record PlaceReservationDocumentConfiguration : DocumentStoreConfiguration;